import json
import os
from wordfreq import top_n_list

# Path to the JSON file
INPUT_FILE = 'app/data/rhyme_levels.json'
OUTPUT_JSON_FILE = 'app/data/rhyme_levels_filtered.json'
OUTPUT_TS_FILE = 'data/rhymes.ts'

def filter_rhymes():
    print("Loading rhyme data...")
    with open(INPUT_FILE, 'r') as f:
        data = json.load(f)

    print("Getting top 10,000 common English words...")
    common_words = set(top_n_list('en', 10000))

    original_word_count = 0
    final_word_count = 0
    removed_words = []

    # Filter all families
    new_data = {}
    
    for key in data.keys():
        if not key.startswith('syllable_'):
            new_data[key] = data[key]
            continue
            
        print(f"Processing {key}...")
        families = data[key]
        new_families = []
        
        for family in families:
            original_words = family['words']
            original_word_count += len(original_words)
            
            filtered_words = []
            for word in original_words:
                if word.lower() in common_words:
                    filtered_words.append(word)
                else:
                    removed_words.append(word)
            
            # Filter slant words if present
            filtered_slant_words = []
            if 'slant_words' in family:
                for word in family['slant_words']:
                    if word.lower() in common_words:
                        filtered_slant_words.append(word)

            if len(filtered_words) >= 2:
                family['words'] = filtered_words
                family['count'] = len(filtered_words)
                family['slant_words'] = filtered_slant_words
                new_families.append(family)
                final_word_count += len(filtered_words)
        
        new_data[key] = new_families

    print(f"Original Word Count: {original_word_count}")
    print(f"Final Word Count: {final_word_count}")
    print(f"Removed {original_word_count - final_word_count} words.")
    
    print("Saving filtered JSON data...")
    with open(OUTPUT_JSON_FILE, 'w') as f:
        json.dump(new_data, f, indent=2)

    print("Generating rhymes.ts...")
    generate_ts_file(new_data)
    print("Done!")

def generate_ts_file(data):
    ts_content = """// A collection of rhyming groups.
// Each array is a group of words that rhyme with each other.
// This file is auto-generated by scripts/filter_rhymes.py

export interface RhymeFamily {
    family_id: string;
    label: string;
    count: number;
    words: string[];
}

export interface RhymeData {
    syllable_1_families: RhymeFamily[];
    syllable_2_families: RhymeFamily[];
    syllable_3_families: RhymeFamily[];
    syllable_4_plus_families: RhymeFamily[];
}

// Exporting as a constant if needed, though usually imported from JSON
export const RHYME_DATA: RhymeData = {
"""
    
    for key in ['syllable_1_families', 'syllable_2_families', 'syllable_3_families', 'syllable_4_plus_families']:
        if key not in data:
            ts_content += f"    {key}: [],\n"
            continue
            
        ts_content += f"    {key}: [\n"
        families = data[key]
        # Limit to first 50 families per category to avoid massive TS file if not needed?
        # User wants a dictionary, so we probably need all of them.
        # But writing 10k words to TS might be slow/large.
        # Since `store.ts` imports JSON, maybe we don't need the full data in TS.
        # But `RhymeGrid` might use it? No, `RhymeGrid` uses store.
        # So let's just keep the TS file lightweight or just definitions?
        # The previous version exported `RHYME_GROUPS` which was just 1-syllable.
        # I'll export the full data but maybe compact it.
        
        for i, family in enumerate(families):
            words_str = ", ".join([f'"{w}"' for w in family['words']])
            ts_content += f"        {{\n"
            ts_content += f"            family_id: \"{family['family_id']}\",\n"
            ts_content += f"            label: \"{family['label']}\",\n"
            ts_content += f"            count: {family['count']},\n"
            ts_content += f"            words: [{words_str}]\n"
            ts_content += f"        }}"
            if i < len(families) - 1:
                ts_content += ",\n"
            else:
                ts_content += "\n"
        ts_content += "    ],\n"

    ts_content += "};\n"

    with open(OUTPUT_TS_FILE, 'w') as f:
        f.write(ts_content)

if __name__ == "__main__":
    filter_rhymes()
